Wri 462  submenu
wri/wri_sites pull request #298
Opened 2024-07-31 00:43 UTC by komejo

## What issue(s) does this solve?
Replace black bar submenus on mobile for project pages, tweak simple-page mobile dropdown location.

- [x] Issue Number: https://github.com/wri/WRIN/issues/462

## What is the new behavior?
 - Subpage menus on /aqueduct and /toolbox/setting-enterprise-water-targets are a dropdown on screen sizes under 48 rems.
 - The menu dropdown appears above the "About us" title on /about on mobile, and continues to be a dropdown until we hit 48rems screen size.

## Profile requirements:

- Does deploying this change require a change to config at the site level (choose one)?
  - [x] No config change is required.
  - [ ] Yes, and I have written an update hook to apply these config changes.
  - [ ] Yes, and I've included updating instructions to be added to the release notes. The next release will need to be a major version increase. (Only do this in special cases.)

## Site-level pull requests for testing. Only merge when these PRs are approved:

Create or update any site-level pull requests following [the documentation](https://github.com/wri/WRIN/wiki/WRI-Dev-Workflow-(Thinkshout)#generating-a-multidev-for-wri_sites-work-review)

- [ ] Flagship PR:

## Checked on develop (TA to do)

- [ ] Brasil
- [ ] China
- [ ] Indonesia

2024-08-01 17:02 UTC, mariacha requested changes
This looks and works great! It'll be so nice to eventually phase out that side-scroll stuff, which I've always hated. Anyway, I failed to mention one missing case on subpages, but otherwise this is looking great!

2024-08-07 18:51 UTC, komejo commented on modules/wri_publication/templates/wri-publication-columns.html.twig
> +                {{ drupal_block('menu_block:' ~ menu_title, {level: 1, expand_all_items: 1, depth: 0, parent: menu_title ~ ':' ~ menu_link, render_parent: 0, follow_parent: 'child', follow: 0, label:
Done!

2024-08-13 18:20 UTC, mariacha requested changes
Much better, and I found more things once I got in there and tested it out!

- [ ] For pages like https://web.wriflagship.localhost/about/mission-values can you hide the "About us" breadcrumb on mobile and add in the top-level link back to the About page like this one?

<img width="486" alt="Screenshot 2024-08-13 at 11 15 33 AM" src="https://github.com/user-attachments/assets/49cb3a8a-8dcf-4d2e-8564-f7195c544b8d">

- [ ] I also think the double-indentation for the child menu is going to give us trouble. Can you change that so "Aqueduct" and "Aqueduct Tools" are all left-aligned?

- [ ] Finally, since this dropdown is going to be more prevalent in the site, let's fix this old issue:

https://github.com/wri/WRIN/issues/283

2024-08-14 20:40 UTC, mariacha approved these changes
Very well done!

2024-08-14 20:40 UTC, merged