Wri #916  external pubs
wri/wri_sites pull request #299
Opened 2024-07-31 21:54 UTC by komejo

## What issue(s) does this solve?
Authors (Person Content type) use variations of their names in print, so we are not showing all of their External Publications.

- [ ] Issue Number: https://github.com/wri/wriflagship/issues/916

## What is the new behavior?
 - Adds two new fields to the Person content type: Alternative First Names, Alternative Last Names. 
 - Places those in a new tab: "Aliases"
 - Updates the external Pubs JSON to be a cached version ( https://files.wri.org/external-publications/externalpubs.json)
 - Modifies the code in `ExternalPubBlock.php` to look for all the available combination of names.
 - Also tweaks the layout of the External pubs so they correctly match the page width. 

## Profile requirements:

- Does deploying this change require a change to config at the site level (choose one)?
  - [ ] No config change is required.
  - [x] Yes, and I have written an update hook to apply these config changes.
  - [ ] Yes, and I've included updating instructions to be added to the release notes. The next release will need to be a major version increase. (Only do this in special cases.)

## Site-level pull requests for testing. Only merge when these PRs are approved:

Create or update any site-level pull requests following [the documentation](https://github.com/wri/WRIN/wiki/WRI-Dev-Workflow-(Thinkshout)#generating-a-multidev-for-wri_sites-work-review)

- [ ] Flagship PR: 

## Checked on develop (TA to do)

- [ ] Brasil
- [ ] China
- [ ] Indonesia

2024-08-01 16:12 UTC, mariacha requested changes
There's one PHPCS error, and I left a bunch of notes about things that will make the second test fail (installing from scratch). Those are all things you couldn't possibly know about, since they're Flagship vs. IO specific.

2024-08-01 16:12 UTC, mariacha commented on modules/wri_person/config/install/core.entity_form_display.node.person.default.yml
> +    group_publishing:
This publishing group is WRI specific too, so might give you grief during site install. If not, you can leave it.

2024-08-01 16:12 UTC, mariacha commented on modules/wri_person/wri_person.install
> +    'third_party_settings#field_group#group_more#group_aliases',
I think you don't need `group_more` in here? That should fix the missing Alias tab.

2024-08-01 18:13 UTC, komejo commented on modules/wri_external_pub/src/Plugin/Block/ExternalPubBlock.php
> +      $authAltLast = $node->field_alt_last_names->value;
Ahh, you're right - I got so excited it worked that I forgot to check multiple! I've updated it to loop through all of the potential combinations of First and Last names.

2024-08-01 19:06 UTC, komejo commented
@mariacha W00t! 
![Screenshot 2024-08-01 at 12 06 26 PM](https://github.com/user-attachments/assets/25f7b4fc-449a-4f01-b943-92d859ebabdf)

2024-08-20 19:50 UTC, mariacha approved these changes

2024-08-20 19:53 UTC, merged